version: "3"
services:
  mysql:
    image: wodby/mariadb:10.6
    container_name: "${APP_NAME}_mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./data:/backup
    ports:
      - "3305:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
    depends_on:
      - mysql
    ports:
      - "20001:80"
  php:
    image: wodby/php:8-4.40.4
    container_name: "${APP_NAME}_php"
    environment:
      DB_HOST: mysql
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_DATABASE
      DB_DRIVER: $DB_DRIVER
      PHP_MEMORY_LIMIT: 10240M
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: wodby/nginx:1.21
    container_name: "${APP_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.backend=${APP_NAME}_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${APP_URL}'
    ports:
      - '80:80'
